
CREATE TABLE IF NOT EXISTS "bills"
(
 id        int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 bill_name text NOT NULL,
 bill_amt  int NOT NULL,
 amt_paid  int NOT NULL DEFAULT 0,
 month     text NOT NULL,
 user_id   integer NOT NULL,
 year      integer NOT NULL DEFAULT 2021,
 date      date NULL,
 paid      boolean NOT NULL DEFAULT false,
 CONSTRAINT PK_bills PRIMARY KEY ( "id" ),
 CONSTRAINT FK_19 FOREIGN KEY ( user_id ) REFERENCES "user" ( user_id )
);

CREATE INDEX fkIdx_20 ON bills
(
 user_id
);





