
CREATE TABLE IF NOT EXISTS income
(
 "id"       int NOT NULL GENERATED BY DEFAULT AS IDENTITY, 
 source   text NOT NULL,
 amount   integer NOT NULL,
 user_id  integer NOT NULL,
 month    text NOT NULL,
 year     integer NOT NULL DEFAULT 2021,
 received boolean NOT NULL DEFAULT false,
 date     date NULL,
 CONSTRAINT PK_income PRIMARY KEY ( "id" ),
 CONSTRAINT FK_28 FOREIGN KEY ( user_id ) REFERENCES "user" ( user_id )
);

CREATE INDEX fkIdx_29 ON income
(
 user_id
);




