CREATE TABLE IF NOT EXISTS debt
(
 "id"          int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 name        text NOT NULL,
 start_bal   int NOT NULL,
 curr_bal    int NOT NULL,
 monthly_min int NOT NULL,
 amt_paid    int NOT NULL DEFAULT 0,
 user_id     integer NOT NULL,
 month       text NOT NULL,
 year        integer NOT NULL DEFAULT 2021,
 paid        boolean NOT NULL DEFAULT false,
 date        date NULL,
 CONSTRAINT PK_debt PRIMARY KEY ( "id" ),
 CONSTRAINT FK_39 FOREIGN KEY ( user_id ) REFERENCES user ( user_id )
);

CREATE INDEX fkIdx_40 ON debt
(
 user_id
);





